<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use Illuminate\Database\Seeder;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            // Ngũ cốc & Tinh bột
            [
                'name' => 'Gạo tẻ',
                'code' => 'NL001',
                'description' => 'Gạo tẻ chất lượng cao',
                'unit' => 'kg',
                'unit_price' => 25000,
                'min_stock' => 50,
                'max_stock' => 200,
                'status' => 'active',
            ],
            [
                'name' => 'Bún tươi',
                'code' => 'NL002',
                'description' => 'Bún tươi làm từ gạo',
                'unit' => 'kg',
                'unit_price' => 30000,
                'min_stock' => 20,
                'max_stock' => 100,
                'status' => 'active',
            ],
            [
                'name' => 'Phở khô',
                'code' => 'NL003',
                'description' => 'Phở khô đóng gói',
                'unit' => 'gói',
                'unit_price' => 15000,
                'min_stock' => 30,
                'max_stock' => 150,
                'status' => 'active',
            ],
            [
                'name' => 'Bánh mì',
                'code' => 'NL004',
                'description' => 'Bánh mì tươi',
                'unit' => 'cái',
                'unit_price' => 5000,
                'min_stock' => 50,
                'max_stock' => 200,
                'status' => 'active',
            ],

            // Thịt
            [
                'name' => 'Thịt heo ba chỉ',
                'code' => 'NL005',
                'description' => 'Thịt heo ba chỉ tươi',
                'unit' => 'kg',
                'unit_price' => 150000,
                'min_stock' => 10,
                'max_stock' => 50,
                'status' => 'active',
            ],
            [
                'name' => 'Thịt bò',
                'code' => 'NL006',
                'description' => 'Thịt bò tươi',
                'unit' => 'kg',
                'unit_price' => 350000,
                'min_stock' => 5,
                'max_stock' => 30,
                'status' => 'active',
            ],
            [
                'name' => 'Thịt gà',
                'code' => 'NL007',
                'description' => 'Thịt gà tươi',
                'unit' => 'kg',
                'unit_price' => 120000,
                'min_stock' => 8,
                'max_stock' => 40,
                'status' => 'active',
            ],
            [
                'name' => 'Xúc xích',
                'code' => 'NL008',
                'description' => 'Xúc xích các loại',
                'unit' => 'cái',
                'unit_price' => 8000,
                'min_stock' => 50,
                'max_stock' => 200,
                'status' => 'active',
            ],

            // Hải sản
            [
                'name' => 'Tôm sú',
                'code' => 'NL009',
                'description' => 'Tôm sú tươi sống',
                'unit' => 'kg',
                'unit_price' => 450000,
                'min_stock' => 5,
                'max_stock' => 25,
                'status' => 'active',
            ],
            [
                'name' => 'Cá basa',
                'code' => 'NL010',
                'description' => 'Cá basa tươi',
                'unit' => 'kg',
                'unit_price' => 120000,
                'min_stock' => 8,
                'max_stock' => 40,
                'status' => 'active',
            ],
            [
                'name' => 'Cua biển',
                'code' => 'NL011',
                'description' => 'Cua biển tươi sống',
                'unit' => 'kg',
                'unit_price' => 500000,
                'min_stock' => 3,
                'max_stock' => 20,
                'status' => 'active',
            ],
            [
                'name' => 'Mực tươi',
                'code' => 'NL012',
                'description' => 'Mực tươi',
                'unit' => 'kg',
                'unit_price' => 280000,
                'min_stock' => 5,
                'max_stock' => 30,
                'status' => 'active',
            ],

            // Rau củ
            [
                'name' => 'Rau xà lách',
                'code' => 'NL013',
                'description' => 'Rau xà lách tươi',
                'unit' => 'kg',
                'unit_price' => 40000,
                'min_stock' => 5,
                'max_stock' => 30,
                'status' => 'active',
            ],
            [
                'name' => 'Rau thơm',
                'code' => 'NL014',
                'description' => 'Rau thơm các loại',
                'unit' => 'kg',
                'unit_price' => 50000,
                'min_stock' => 3,
                'max_stock' => 20,
                'status' => 'active',
            ],
            [
                'name' => 'Cà chua',
                'code' => 'NL015',
                'description' => 'Cà chua tươi',
                'unit' => 'kg',
                'unit_price' => 35000,
                'min_stock' => 10,
                'max_stock' => 50,
                'status' => 'active',
            ],
            [
                'name' => 'Hành tây',
                'code' => 'NL016',
                'description' => 'Hành tây',
                'unit' => 'kg',
                'unit_price' => 30000,
                'min_stock' => 10,
                'max_stock' => 50,
                'status' => 'active',
            ],
            [
                'name' => 'Tỏi',
                'code' => 'NL017',
                'description' => 'Tỏi tươi',
                'unit' => 'kg',
                'unit_price' => 60000,
                'min_stock' => 5,
                'max_stock' => 30,
                'status' => 'active',
            ],
            [
                'name' => 'Ớt',
                'code' => 'NL018',
                'description' => 'Ớt tươi',
                'unit' => 'kg',
                'unit_price' => 80000,
                'min_stock' => 2,
                'max_stock' => 15,
                'status' => 'active',
            ],
            [
                'name' => 'Chanh',
                'code' => 'NL019',
                'description' => 'Chanh tươi',
                'unit' => 'kg',
                'unit_price' => 40000,
                'min_stock' => 5,
                'max_stock' => 30,
                'status' => 'active',
            ],

            // Gia vị & Nước chấm
            [
                'name' => 'Nước mắm',
                'code' => 'NL020',
                'description' => 'Nước mắm Phú Quốc',
                'unit' => 'chai',
                'unit_price' => 120000,
                'min_stock' => 10,
                'max_stock' => 50,
                'status' => 'active',
            ],
            [
                'name' => 'Đường',
                'code' => 'NL021',
                'description' => 'Đường trắng',
                'unit' => 'kg',
                'unit_price' => 25000,
                'min_stock' => 20,
                'max_stock' => 100,
                'status' => 'active',
            ],
            [
                'name' => 'Muối',
                'code' => 'NL022',
                'description' => 'Muối ăn',
                'unit' => 'kg',
                'unit_price' => 10000,
                'min_stock' => 10,
                'max_stock' => 50,
                'status' => 'active',
            ],
            [
                'name' => 'Hạt nêm',
                'code' => 'NL023',
                'description' => 'Hạt nêm các loại',
                'unit' => 'gói',
                'unit_price' => 35000,
                'min_stock' => 20,
                'max_stock' => 100,
                'status' => 'active',
            ],
            [
                'name' => 'Dầu ăn',
                'code' => 'NL024',
                'description' => 'Dầu ăn thực vật',
                'unit' => 'chai',
                'unit_price' => 80000,
                'min_stock' => 15,
                'max_stock' => 80,
                'status' => 'active',
            ],
            [
                'name' => 'Tương ớt',
                'code' => 'NL025',
                'description' => 'Tương ớt Cholimex',
                'unit' => 'chai',
                'unit_price' => 25000,
                'min_stock' => 20,
                'max_stock' => 100,
                'status' => 'active',
            ],
            [
                'name' => 'Tương đen',
                'code' => 'NL026',
                'description' => 'Tương đen',
                'unit' => 'chai',
                'unit_price' => 30000,
                'min_stock' => 15,
                'max_stock' => 80,
                'status' => 'active',
            ],

            // Đồ uống
            [
                'name' => 'Coca Cola',
                'code' => 'NL027',
                'description' => 'Coca Cola lon',
                'unit' => 'lon',
                'unit_price' => 12000,
                'min_stock' => 50,
                'max_stock' => 300,
                'status' => 'active',
            ],
            [
                'name' => 'Pepsi',
                'code' => 'NL028',
                'description' => 'Pepsi lon',
                'unit' => 'lon',
                'unit_price' => 12000,
                'min_stock' => 50,
                'max_stock' => 300,
                'status' => 'active',
            ],
            [
                'name' => '7Up',
                'code' => 'NL029',
                'description' => '7Up lon',
                'unit' => 'lon',
                'unit_price' => 12000,
                'min_stock' => 30,
                'max_stock' => 200,
                'status' => 'active',
            ],
            [
                'name' => 'Nước suối',
                'code' => 'NL030',
                'description' => 'Nước suối đóng chai',
                'unit' => 'chai',
                'unit_price' => 8000,
                'min_stock' => 50,
                'max_stock' => 300,
                'status' => 'active',
            ],
            [
                'name' => 'Cà phê nguyên chất',
                'code' => 'NL031',
                'description' => 'Cà phê rang xay',
                'unit' => 'kg',
                'unit_price' => 200000,
                'min_stock' => 5,
                'max_stock' => 30,
                'status' => 'active',
            ],
            [
                'name' => 'Trà túi lọc',
                'code' => 'NL032',
                'description' => 'Trà túi lọc các loại',
                'unit' => 'gói',
                'unit_price' => 50000,
                'min_stock' => 20,
                'max_stock' => 100,
                'status' => 'active',
            ],

            // Khác
            [
                'name' => 'Trứng gà',
                'code' => 'NL033',
                'description' => 'Trứng gà tươi',
                'unit' => 'cái',
                'unit_price' => 3000,
                'min_stock' => 50,
                'max_stock' => 200,
                'status' => 'active',
            ],
            [
                'name' => 'Bánh tráng',
                'code' => 'NL034',
                'description' => 'Bánh tráng cuốn',
                'unit' => 'gói',
                'unit_price' => 25000,
                'min_stock' => 20,
                'max_stock' => 100,
                'status' => 'active',
            ],
            [
                'name' => 'Nước dừa',
                'code' => 'NL035',
                'description' => 'Nước dừa tươi',
                'unit' => 'trái',
                'unit_price' => 15000,
                'min_stock' => 20,
                'max_stock' => 100,
                'status' => 'active',
            ],
            [
                'name' => 'Sữa tươi',
                'code' => 'NL036',
                'description' => 'Sữa tươi đóng hộp',
                'unit' => 'hộp',
                'unit_price' => 18000,
                'min_stock' => 30,
                'max_stock' => 150,
                'status' => 'active',
            ],
            [
                'name' => 'Kem',
                'code' => 'NL037',
                'description' => 'Kem các vị',
                'unit' => 'hộp',
                'unit_price' => 45000,
                'min_stock' => 10,
                'max_stock' => 50,
                'status' => 'active',
            ],
        ];

        foreach ($ingredients as $ingredient) {
            Ingredient::create($ingredient);
        }

        $this->command->info('Đã tạo ' . count($ingredients) . ' nguyên liệu mẫu!');
    }
}
